import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/ui/themes";
import { ThemeProvider } from "@/provider/theme-provider";
// import NavBar from "@/src/componemts/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider appearance={{theme : dark}}>

         <html lang="en" className="dark"
         suppressHydrationWarning
         >
          <body className={inter.className}>
    <ThemeProvider
      attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
      >
      
       
        {children}
    </ThemeProvider>
      </body>
      
    </html>

    </ClerkProvider>
   
  );
}
